### ISSUE TITLE
NullPointerException in com.openshift.jenkins.plugins.pipeline.Auth.allowCertificate(Auth.java:86)

### ISSUE THREAD

**Issue by jim-minter** [openshift/jenkins-plugin#18]
Started by user ha:AAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzeEgZu/dLi1CL9xJTczDwACG0V4sAAAAA=Jenkins Admin
Building in workspace /var/lib/jenkins/jobs/OpenShift Sample/workspace

BUILD STEP:  OpenShiftScaler in perform for frontend wanting to get to replica count 0 on namespace test
ERROR: Build step failed with exception
ha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=com.openshift.restclient.OpenShiftException: Could not get resource frontend in namespace test: javax.net.ssl.SSLException: java.lang.NullPointerException
    at com.openshift.internal.restclient.DefaultClient.createOpenShiftException(DefaultClient.java:480)
    at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:303)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftScaler.coreLogic(OpenShiftScaler.java:74)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:143)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)
Caused by: com.openshift.internal.restclient.http.HttpClientException: javax.net.ssl.SSLException: java.lang.NullPointerException
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.createException(UrlConnectionHttpClient.java:230)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:161)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:140)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.get(UrlConnectionHttpClient.java:102)
    at com.openshift.internal.restclient.DefaultClient.getVersion(DefaultClient.java:371)
    at com.openshift.internal.restclient.DefaultClient.getOpenShiftVersions(DefaultClient.java:345)
    at com.openshift.internal.restclient.DefaultClient.getOpenShiftAPIVersion(DefaultClient.java:361)
    at com.openshift.internal.restclient.DefaultClient.getTypeMappings(DefaultClient.java:405)
    at com.openshift.internal.restclient.DefaultClient.getTypeMappings(DefaultClient.java:400)
    at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:294)
    ... 11 more
Caused by: javax.net.ssl.SSLException: java.lang.NullPointerException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.createException(UrlConnectionHttpClient.java:213)
    ... 20 more
Caused by: javax.net.ssl.SSLException: java.lang.NullPointerException
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:157)
    ... 19 more
Caused by: java.lang.NullPointerException
    at com.openshift.jenkins.plugins.pipeline.Auth.allowCertificate(Auth.java:86)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient$CallbackTrustManager.checkServerTrusted(UrlConnectionHttpClient.java:449)
    at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:922)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
    ... 26 more
Build step 'Scale deployments in OpenShift' marked build as failure
Finished: FAILURE

**Comment by jim-minter** [comment]
Using OSE 3.1.1 (Jenkins plugin 1.0.4), demobuilder image.

In https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/Auth.java#L86 , shouldn't

if (this.listener.getLogger() != null)

read

if (this.listener != null)

?

**Comment by jim-minter** [comment]
ATM not quite sure why I'm hitting this bug and others don't appear to have done.  The pod was created via using the jenkins-ephemeral instant app.

**Comment by jim-minter** [comment]
Ah, FWIW this triggers if the OpenShift node cert is missing the chained CA certificate.

**Comment by gabemontero** [comment]
hey @jim-minter - yep, you have basically captured the 2 key points here.  But I'll elaborate a bit:

1) Yes, the if check at https://github.com/openshift/jenkins-plugin/blob/master/src/main/java/com/openshift/jenkins/plugins/pipeline/Auth.java#L86 should be changed as you articulated; the Auth class uses the setting of the listener instance var to dictate whether it does verbose logging or not (there are some scenarios where the "verbose" flag set on the build steps is not accessible);  easy enough fix I'll put in the queue

2)  Your point about that the OpenShift node cert is missing is the key to why others haven't seen it as yet; to date, users have had that set up, and we've not allowed insecure connections with the plugin;  to that end, even without the NPE, your job would have ultimately failed, citing a failed SSL negotiation ... at the moment, we allow insecure access if the plugin is not running out of our jenkins image, but if we are running out of the jenkins image, we currently require it.

Let me know your take on allowing insecure access.  There has been some back and forth about whether to allow insecure access (the kube plugin from cloudbees does for example), importing of certs, etc.  So the plugin may be getting enhanced here.

But in the short term, I'll get the NPE fix in the queue.

**Comment by gabemontero** [comment]
just pushed the NPE fix to this repo with commit 4b98d9cc3df3ca3729cb24731ba23e27c698f7d3.

marking this item closed;  i'm following up with @jim-minter outside of this issue on some additional jenkins plugin / image updates
