### ISSUE TITLE
Builds are end with timeout error

### ISSUE THREAD

**Issue by livelace** [openshift/jenkins-plugin#50]
See http://openshift-master1.i.drweb.ru:8080/job/images/job/base/76/

---

Started by upstream project "images/base-meta" build number 25
originally caused by:
 Started by user admin
Running as admin
[EnvInject] - Loading node environment variables.
Building remotely on openshift-node2 in workspace http://openshift-master1.i.drweb.ru:8080/job/images/job/base/ws/

Starting the "Trigger OpenShift Build" step with build config "ubuntu-base" from the project "images".
  Started build "ubuntu-base-36" and waiting for build completion followed by a new deployment ...
ERROR: Build step failed with exception
com.openshift.internal.restclient.http.HttpClientException: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: timed out waiting for build ubuntu-base-36 to start after 10s","reason":"Timeout","details":{"retryAfterSeconds":1},"code":504}

```
at com.openshift.internal.restclient.http.UrlConnectionHttpClient.createException(UrlConnectionHttpClient.java:278)
at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:211)
at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:187)
at com.openshift.internal.restclient.http.UrlConnectionHttpClient.get(UrlConnectionHttpClient.java:149)
at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftBuilder.dumpLogs(IOpenShiftBuilder.java:173)
at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftBuilder.waitOnBuild(IOpenShiftBuilder.java:121)
at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftBuilder.coreLogic(IOpenShiftBuilder.java:270)
at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:241)
at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:254)
at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:91)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
at hudson.model.Build$BuildExecution.build(Build.java:205)
at hudson.model.Build$BuildExecution.doRun(Build.java:162)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
at hudson.model.Run.execute(Run.java:1738)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:410)
```

Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://openshift-master1.i.drweb.ru:8443/oapi/v1/namespaces/images/builds/ubuntu-base-36/log
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.openshift.internal.restclient.http.UrlConnectionHttpClient.request(UrlConnectionHttpClient.java:207)
    ... 17 more
Build step 'Trigger OpenShift Build' marked build as failure

**Comment by livelace** [comment]
Version 1.0.21 

STR: mutiple builds inside mutijob project.

Builds are marked as failed, but the builds are still working.

**Comment by gabemontero** [comment]
Definitely a timing thing.  I am _NOT_ seeing in my repro attempts here.

However, based on code inspection, I could see that if say the build was slow in starting, we might get something like a 504, where as subsequent http gets would work, and currently the build log logic would not shield the outlying logic from those initial exceptions/hiccups.

I can probably cook up a pre-release change soon.

**Comment by gabemontero** [comment]
OK, @livelace, I delivered a fix with https://github.com/openshift/jenkins-plugin/commit/a1131ed0768386d5946737c6a08858002c5b67a0

Try this pre-release version:  https://ci.openshift.redhat.com/jenkins/job/openshift-pipeline-plugin/26/s3/download/openshift-pipeline.hpi

**Comment by livelace** [comment]
I launched three queues of builds and they are working now without problems. There are about 60 builds in these queues. I will write about problems as soon as they will arise :) Thanks!

**Comment by livelace** [comment]
All tasks completed without errors. It's worked!

**Comment by livelace** [comment]
@gabemontero  May I ask you about execution specific scripts inside deployment configuration ?

**Comment by gabemontero** [comment]
@livelace - good news that the build log tweak worked for you.

I'm not familiar with execution scripts within a deployment config.  I would recommend post the question on our [mailing list](https://lists.openshift.redhat.com/openshiftmm/listinfo/dev) or filing an issue on the origin repo.
