### ISSUE TITLE
[jenkins workflow] NPE OpenShiftBuilder.inspectBuildEnvAndOverrideFields(OpenShiftBuilder.java:110)

### ISSUE THREAD

**Issue by rawlingsj** [openshift/jenkins-plugin#6]
Using plugin v1.0.3

I've got a simple workflow however one thing I noticed is that in the help it suggested an API server name of `https://openshift.default.svc.cluster.local` where as I dont have an openshift service but a kubernetes one instead, I'm using OpenShift Origin v1.1.0.1

```
node ('kubernetes'){

  step([$class: 'com.openshift.jenkins.plugins.pipeline.OpenShiftBuilder', apiURL:'https://kubernetes.default', bldCfg:'node-app', namespace:'default', authToken:'blahblah', verbose:'true', commitID:'', buildName:'', showBuildLogs:'true'])

}

```

which throws this error when run..

```
Started by user anonymous
[Workflow] Allocate node : Start
Running on 1e01b838afcd5 in /home/jenkins/workspace/workspace/s2i-build
[Workflow] node {
[Workflow] step
[Workflow] } //node
[Workflow] Allocate node : End
[Workflow] End of Workflow
java.lang.NullPointerException
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBuilder.inspectBuildEnvAndOverrideFields(OpenShiftBuilder.java:110)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBuilder.coreBuildLogic(OpenShiftBuilder.java:168)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBuilder.perform(OpenShiftBuilder.java:404)
    at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:68)
    at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:59)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:49)
    at hudson.security.ACL.impersonate(ACL.java:213)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

**Comment by gabemontero** [comment]
hi @rawlingsj - thx for the interest ... I believe that NPE is fixed with this commit - https://github.com/openshift/jenkins-plugin/commit/e437d87714fa029beb48c53a3d3cdee9c84588eb

Given the complexity of the change (I addressed several other issues besides the NPE), I've not created a new version in the jenkins UC yet, as some more testing is occurring,including with another early user outside of my org.

Is it critical for you to pull the version from jenkins update center vs. building the plugin locally and installing that way?  If you have to wait for the UC, I'm currently anticipating updating the version there some time next week.

thanks.

**Comment by rawlingsj** [comment]
@gabemontero building locally is totally fine!  Thanks for the quick response, I'll give it a whirl first thing.

**Comment by gabemontero** [comment]
@rawlingsj cool deal! ... and this way, the more testers the merrier ;-)

**Comment by rawlingsj** [comment]
The development version worked perfectly.  Thanks!

**Comment by gabemontero** [comment]
Cool deal!
