### ISSUE TITLE
Create OpenShift Resource throws exception even when SKIP_TLS=1

### ISSUE THREAD

**Issue by jupierce** [openshift/jenkins-plugin#72]
The operation succeeds, but an exception is thrown during fetchApiJsonFromApiServer

Logs:

```
Started by user admin
Building in workspace /var/jenkins_home/workspace/creator
build env vars:  {=, BUILD_DISPLAY_NAME=#1, BUILD_ID=1, BUILD_NUMBER=1, BUILD_TAG=jenkins-creator-1, BUILD_URL=http://localhost:49001/job/creator/1/, CA_CERTIFICATES_JAVA_VERSION=20140324, CLASSPATH=, COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log, EXECUTOR_NUMBER=1, HOME=/var/jenkins_home, HOSTNAME=ac60e305051e, HUDSON_HOME=/var/jenkins_home, HUDSON_SERVER_COOKIE=e9cef694bbb24663, HUDSON_URL=http://localhost:49001/, JAVA_DEBIAN_VERSION=8u102-b14.1-1~bpo8+1, JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64, JAVA_VERSION=8u102, JENKINS_HOME=/var/jenkins_home, JENKINS_SERVER_COOKIE=e9cef694bbb24663, JENKINS_SLAVE_AGENT_PORT=50000, JENKINS_UC=https://updates.jenkins.io, JENKINS_URL=http://localhost:49001/, JENKINS_VERSION=2.7.4, JOB_BASE_NAME=creator, JOB_NAME=creator, JOB_URL=http://localhost:49001/job/creator/, LANG=C.UTF-8, NODE_LABELS=master, NODE_NAME=master, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, PWD=/, SHLVL=0, SKIP_TLS=1, TERM=xterm, TINI_SHA=fa23d1e20732501c3bb8eeeca423c89ac80ed452, TINI_VERSION=0.9.0, WORKSPACE=/var/jenkins_home/workspace/creator}
computer env vars:  {CA_CERTIFICATES_JAVA_VERSION=20140324, COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log, HOME=/var/jenkins_home, HOSTNAME=ac60e305051e, JAVA_DEBIAN_VERSION=8u102-b14.1-1~bpo8+1, JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64, JAVA_VERSION=8u102, JENKINS_HOME=/var/jenkins_home, JENKINS_SLAVE_AGENT_PORT=50000, JENKINS_UC=https://updates.jenkins.io, JENKINS_VERSION=2.7.4, LANG=C.UTF-8, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, PWD=/, SHLVL=0, TERM=xterm, TINI_SHA=fa23d1e20732501c3bb8eeeca423c89ac80ed452, TINI_VERSION=0.9.0}
Creating new auth instance with SKIP_TLS=true


OpenShift Pipeline Plugin: env vars for this job:  {=, BUILD_DISPLAY_NAME=#1, BUILD_ID=1, BUILD_NUMBER=1, BUILD_TAG=jenkins-creator-1, BUILD_URL=http://localhost:49001/job/creator/1/, CA_CERTIFICATES_JAVA_VERSION=20140324, CLASSPATH=, COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log, EXECUTOR_NUMBER=1, HOME=/var/jenkins_home, HOSTNAME=ac60e305051e, HUDSON_HOME=/var/jenkins_home, HUDSON_SERVER_COOKIE=e9cef694bbb24663, HUDSON_URL=http://localhost:49001/, JAVA_DEBIAN_VERSION=8u102-b14.1-1~bpo8+1, JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64, JAVA_VERSION=8u102, JENKINS_HOME=/var/jenkins_home, JENKINS_SERVER_COOKIE=e9cef694bbb24663, JENKINS_SLAVE_AGENT_PORT=50000, JENKINS_UC=https://updates.jenkins.io, JENKINS_URL=http://localhost:49001/, JENKINS_VERSION=2.7.4, JOB_BASE_NAME=creator, JOB_NAME=creator, JOB_URL=http://localhost:49001/job/creator/, LANG=C.UTF-8, NODE_LABELS=master, NODE_NAME=master, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, PWD=/, SHLVL=0, SKIP_TLS=1, TERM=xterm, TINI_SHA=fa23d1e20732501c3bb8eeeca423c89ac80ed452, TINI_VERSION=0.9.0, WORKSPACE=/var/jenkins_home/workspace/creator}


Starting "Create OpenShift Resource(s)" with the project "myproject".
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
    at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
    at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:54)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.execute(RealCall.java:60)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.httpGet(IOpenShiftPlugin.java:686)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.fetchApiJsonFromApiServer(IOpenShiftApiObjHandler.java:23)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.updateApiTypes(IOpenShiftApiObjHandler.java:66)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftCreator.coreLogic(IOpenShiftCreator.java:68)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:322)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:91)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
    at sun.security.validator.Validator.validate(Validator.java:260)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
    ... 46 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
    ... 52 more
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
    at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
    at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:54)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.execute(RealCall.java:60)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.httpGet(IOpenShiftPlugin.java:686)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.fetchApiJsonFromApiServer(IOpenShiftApiObjHandler.java:23)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftApiObjHandler.updateApiTypes(IOpenShiftApiObjHandler.java:67)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftCreator.coreLogic(IOpenShiftCreator.java:68)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:322)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:91)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
    at sun.security.validator.Validator.validate(Validator.java:260)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
    ... 46 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
    ... 52 more

OpenShiftCreator calling create on for type imagestreams and resource {
    "apiVersion" : "v1",
    "kind" : "ImageStream",
    "metadata" : {"name" : "c1"},
    "spec" : {"tags" : [{
        "from" : {
            "kind" : "DockerImage",
            "name" : "172.30.5.151:5000/myproject/ruby-hello-world:latest"
        },
        "importPolicy" : {},
        "name" : "latest"
    }]},
    "status" : {"dockerImageRepository" : ""}
}
Auth - allowCertificate with incoming chain of len  2
Auth - in skip tls mode, returning true
  Created a "ImageStream"


Exiting "Create OpenShift Resource(s)" successfully, with 1 resource(s) created.
Finished: SUCCESS
```

**Comment by gabemontero** [comment]
minor note - I don't believe the exception would have appeared if verbose was not set to true.

**Comment by gabemontero** [comment]
or would not have been printed I should say, to be more clear

**Comment by bparees** [comment]
Sounds like we should turn it into a cleaner log message (that only shows
up with verbose logging)

Ben Parees | OpenShift

**Comment by gabemontero** [comment]
Perhaps I still mangled it - it _only_ shows up in the current form _if_ verbose logging is on.

As to what shows up, since it is just debug, I'm simply printing the exception stack trace, and was not worried about appearance.

**Comment by jupierce** [comment]
@gabemontero So is this exception expected? Why?

**Comment by gabemontero** [comment]
No, the exception is not expected.  I'm testing a fix now.  The "minor
note" portion of the original
comment was my attempt to classify this as a side bar (probably should have
just used "side bar").

Most likely when I tested this I didn't have verbose on and missed this
exception.
