### ISSUE TITLE
Why any operation has the same error in jenkins？connected to openshift is error?

### ISSUE THREAD

**Issue by gyj0825** [openshift/jenkins-plugin#81]
I'm running jenkins outside the openshift.Any operation has the same error.
Set SKIP_TLS=true will see same error also,why?。

I add policy to serviceaccount/default also。
$ oc policy add-role-to-user edit system:serviceaccount:jenkins:default

When connected to openshift,do you still need the port other than 8443？

version info:
jenkins version: 2.7.2  openshift version: 3.2.1.1

**jenkins project config:**
![image](https://cloud.githubusercontent.com/assets/16714430/19219326/a8e02bf6-8e42-11e6-935c-92e1ea042499.png)
![image](https://cloud.githubusercontent.com/assets/16714430/19219305/5370b348-8e42-11e6-878c-8ccbf1d99e3b.png)

**jenkins error logs:**
Started by user test
Building in workspace /var/lib/jenkins/workspace/openshift-build
build env vars:  {_=/etc/alternatives/java, AUTH_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tOTM3ZDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjIzZWYzM2I1LThkYTEtMTFlNi1iOTg5LWIwODNmZWIxNjMyYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpqZW5raW5zOmRlZmF1bHQifQ.AYu4FyLfK8t3CgSUTASJq36ZrkUQGoOa52FXvrwtwisO_V3TQg2uPMd0YPnjdtNprdZGy1m37XklqL8I0wOSfMNeDY3QPL6Z43bnfbt-hRpXAijMRSadPm0pOK5aeZzXywZH2IGH9IaNtHHIa05EVN7nwEGGyIKd779LEuOmhNRcac-WH0tZ3BFKAB4PMkQM_M-96joTf0GP9_tAtvrtGNfOYiU9-qkuPsrdbPtomVqs6rEimy1x-vZx4M30bwPlFyR_PtwADbewRGU9HJZ8OwS06iFKLtlHrCsVVPpwQ1ItccpRQMfulKY_37yrQmOwEoC--n1c0GpbzTK3w2YDPA, BUILD_DISPLAY_NAME=#20, BUILD_ID=20, BUILD_NUMBER=20, BUILD_TAG=jenkins-openshift-build-20, BUILD_URL=http://10.6.124.53:8080/job/openshift-build/20/, CA_CERT=-----BEGIN CERTIFICATE-----
MIIC5jCCAdCgAwIBAgIBATALBgkqhkiG9w0BAQswJjEkMCIGA1UEAwwbb3BlbnNo
aWZ0LXNpZ25lckAxNDY5NDg0NDE2MB4XDTE2MDcyNTIyMDY1NVoXDTIxMDcyNDIy
MDY1NlowJjEkMCIGA1UEAwwbb3BlbnNoaWZ0LXNpZ25lckAxNDY5NDg0NDE2MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnDe3SpdSLD5SWcoodlu/sPDP
GVj+NcxJdR3k567XeNdeBeY68nLrgbATU+tVsRDWCR/7MsEoyzes9S2Q1G0jdIw8
1j422lxa81V6XNRW96cZHcmrSqXoOYN89DutgCQk6Vy66RglJGf7sGYtP9NrwDXe
9rWnlz0+wBByryUmUxEP51TgQ7RQJyxqCrzi1qvFI/UtCmMty+qmCbKYxXHymgiT
X8gkrxz93TVL6k27rSvrsLdJR4Qb5GmftUWgiJsN7cA/zRu3Vy9CJeoIfrsCdCK4
pQAPSlVzsAkG3FLAtaQjK+2Om+rsckQfVNuqMGJtoDUEtoMjtzPssvg3A/wj+QID
AQABoyMwITAOBgNVHQ8BAf8EBAMCAKQwDwYDVR0TAQH/BAUwAwEB/zALBgkqhkiG
9w0BAQsDggEBAG5vGi4tUHm3L26J25d3WlqeMeGVP3hFlAfIBU5072Ffq6XwyZZF
vkbPGquXq8D2FSP2o59OSrXeVHvci2izLfq/xV7NDK90a+jh7w4REuSUaciWaPRd
fh+J+FQdznn2i/Gi/mMeiYsbbKEFkXAWWaYom9tJEuUdcW4mDmm9D0f1ML5CIIbY
nDhNj0GVa/ujmHbGHAYtQWu76GqoCTv0aw/6mvP3xCt6wDKSBD3xVmV4t2eKLjrm
AuYgd3XPjjuOSFpfBUn+rnZHsNWJRJge6IZU3Bcp5wDclzYxE8CJgehC9OzDGbYN
+uHcSNL8kxS1OO7dT9mZxi4iat+zLUS5kGA=
-----END CERTIFICATE-----, CLASSPATH=, EXECUTOR_NUMBER=0, HOME=/var/lib/jenkins, HUDSON_HOME=/var/lib/jenkins, HUDSON_SERVER_COOKIE=0994b19186aa7899, HUDSON_URL=http://10.6.124.53:8080/, JENKINS_HOME=/var/lib/jenkins, JENKINS_SERVER_COOKIE=0994b19186aa7899, JENKINS_URL=http://10.6.124.53:8080/, JOB_BASE_NAME=openshift-build, JOB_NAME=openshift-build, JOB_URL=http://10.6.124.53:8080/job/openshift-build/, LANG=zh_CN.UTF-8, LOGNAME=jenkins, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, NODE_LABELS=master, NODE_NAME=master, PATH=/sbin:/usr/sbin:/bin:/usr/bin, PWD=/, SHELL=/bin/bash, SHLVL=3, TERM=xterm, USER=jenkins, WORKSPACE=/var/lib/jenkins/workspace/openshift-build, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt}
computer env vars:  {_=/etc/alternatives/java, HOME=/var/lib/jenkins, LANG=en_US.UTF-8, LOGNAME=jenkins, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, PATH=/sbin:/usr/sbin:/bin:/usr/bin, PWD=/, SHELL=/bin/bash, SHLVL=3, TERM=xterm, USER=jenkins, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt}
Auth - cert file exists - false, CA_CERT - -----BEGIN CERTIFICATE-----
MIIC5jCCAdCgAwIBAgIBATALBgkqhkiG9w0BAQswJjEkMCIGA1UEAwwbb3BlbnNo
aWZ0LXNpZ25lckAxNDY5NDg0NDE2MB4XDTE2MDcyNTIyMDY1NVoXDTIxMDcyNDIy
MDY1NlowJjEkMCIGA1UEAwwbb3BlbnNoaWZ0LXNpZ25lckAxNDY5NDg0NDE2MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnDe3SpdSLD5SWcoodlu/sPDP
GVj+NcxJdR3k567XeNdeBeY68nLrgbATU+tVsRDWCR/7MsEoyzes9S2Q1G0jdIw8
1j422lxa81V6XNRW96cZHcmrSqXoOYN89DutgCQk6Vy66RglJGf7sGYtP9NrwDXe
9rWnlz0+wBByryUmUxEP51TgQ7RQJyxqCrzi1qvFI/UtCmMty+qmCbKYxXHymgiT
X8gkrxz93TVL6k27rSvrsLdJR4Qb5GmftUWgiJsN7cA/zRu3Vy9CJeoIfrsCdCK4
pQAPSlVzsAkG3FLAtaQjK+2Om+rsckQfVNuqMGJtoDUEtoMjtzPssvg3A/wj+QID
AQABoyMwITAOBgNVHQ8BAf8EBAMCAKQwDwYDVR0TAQH/BAUwAwEB/zALBgkqhkiG
9w0BAQsDggEBAG5vGi4tUHm3L26J25d3WlqeMeGVP3hFlAfIBU5072Ffq6XwyZZF
vkbPGquXq8D2FSP2o59OSrXeVHvci2izLfq/xV7NDK90a+jh7w4REuSUaciWaPRd
fh+J+FQdznn2i/Gi/mMeiYsbbKEFkXAWWaYom9tJEuUdcW4mDmm9D0f1ML5CIIbY
nDhNj0GVa/ujmHbGHAYtQWu76GqoCTv0aw/6mvP3xCt6wDKSBD3xVmV4t2eKLjrm
AuYgd3XPjjuOSFpfBUn+rnZHsNWJRJge6IZU3Bcp5wDclzYxE8CJgehC9OzDGbYN
+uHcSNL8kxS1OO7dT9mZxi4iat+zLUS5kGA=
-----END CERTIFICATE-----
 skip tls - null
Auth - using user inputted cert string

OpenShift Pipeline Plugin: env vars for this job:  {AUTH_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tOTM3ZDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjIzZWYzM2I1LThkYTEtMTFlNi1iOTg5LWIwODNmZWIxNjMyYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpqZW5raW5zOmRlZmF1bHQifQ.AYu4FyLfK8t3CgSUTASJq36ZrkUQGoOa52FXvrwtwisO_V3TQg2uPMd0YPnjdtNprdZGy1m37XklqL8I0wOSfMNeDY3QPL6Z43bnfbt-hRpXAijMRSadPm0pOK5aeZzXywZH2IGH9IaNtHHIa05EVN7nwEGGyIKd779LEuOmhNRcac-WH0tZ3BFKAB4PMkQM_M-96joTf0GP9_tAtvrtGNfOYiU9-qkuPsrdbPtomVqs6rEimy1x-vZx4M30bwPlFyR_PtwADbewRGU9HJZ8OwS06iFKLtlHrCsVVPpwQ1ItccpRQMfulKY_37yrQmOwEoC--n1c0GpbzTK3w2YDPA, BUILD_DISPLAY_NAME=#20, BUILD_ID=20, BUILD_NUMBER=20, BUILD_TAG=jenkins-openshift-build-20, BUILD_URL=http://10.6.124.53:8080/job/openshift-build/20/, CA_CERT=-----BEGIN CERTIFICATE-----
MIIC5jCCAdCgAwIBAgIBATALBgkqhkiG9w0BAQswJjEkMCIGA1UEAwwbb3BlbnNo
aWZ0LXNpZ25lckAxNDY5NDg0NDE2MB4XDTE2MDcyNTIyMDY1NVoXDTIxMDcyNDIy
MDY1NlowJjEkMCIGA1UEAwwbb3BlbnNoaWZ0LXNpZ25lckAxNDY5NDg0NDE2MIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnDe3SpdSLD5SWcoodlu/sPDP
GVj+NcxJdR3k567XeNdeBeY68nLrgbATU+tVsRDWCR/7MsEoyzes9S2Q1G0jdIw8
1j422lxa81V6XNRW96cZHcmrSqXoOYN89DutgCQk6Vy66RglJGf7sGYtP9NrwDXe
9rWnlz0+wBByryUmUxEP51TgQ7RQJyxqCrzi1qvFI/UtCmMty+qmCbKYxXHymgiT
X8gkrxz93TVL6k27rSvrsLdJR4Qb5GmftUWgiJsN7cA/zRu3Vy9CJeoIfrsCdCK4
pQAPSlVzsAkG3FLAtaQjK+2Om+rsckQfVNuqMGJtoDUEtoMjtzPssvg3A/wj+QID
AQABoyMwITAOBgNVHQ8BAf8EBAMCAKQwDwYDVR0TAQH/BAUwAwEB/zALBgkqhkiG
9w0BAQsDggEBAG5vGi4tUHm3L26J25d3WlqeMeGVP3hFlAfIBU5072Ffq6XwyZZF
vkbPGquXq8D2FSP2o59OSrXeVHvci2izLfq/xV7NDK90a+jh7w4REuSUaciWaPRd
fh+J+FQdznn2i/Gi/mMeiYsbbKEFkXAWWaYom9tJEuUdcW4mDmm9D0f1ML5CIIbY
nDhNj0GVa/ujmHbGHAYtQWu76GqoCTv0aw/6mvP3xCt6wDKSBD3xVmV4t2eKLjrm
AuYgd3XPjjuOSFpfBUn+rnZHsNWJRJge6IZU3Bcp5wDclzYxE8CJgehC9OzDGbYN
+uHcSNL8kxS1OO7dT9mZxi4iat+zLUS5kGA=
-----END CERTIFICATE-----, CLASSPATH=, EXECUTOR_NUMBER=0, HOME=/var/lib/jenkins, HUDSON_HOME=/var/lib/jenkins, HUDSON_SERVER_COOKIE=0994b19186aa7899, HUDSON_URL=http://10.6.124.53:8080/, JENKINS_HOME=/var/lib/jenkins, JENKINS_SERVER_COOKIE=0994b19186aa7899, JENKINS_URL=http://10.6.124.53:8080/, JOB_BASE_NAME=openshift-build, JOB_NAME=openshift-build, JOB_URL=http://10.6.124.53:8080/job/openshift-build/, LANG=en_US.UTF-8, LOGNAME=jenkins, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, NODE_LABELS=master, NODE_NAME=master, PATH=/sbin:/usr/sbin:/bin:/usr/bin, PWD=/, SHELL=/bin/bash, SHLVL=3, TERM=xterm, USER=jenkins, WORKSPACE=/var/lib/jenkins/workspace/openshift-build, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, _=/etc/alternatives/java}

Starting "Scale OpenShift Deployment" with deployment config "mskyweb" from the project "jenkins".

OpenShiftScaler wait 180000
 Scaling to "1" replicas and verifying the replica count is reached ...
ERROR: Build step failed with exception
com.openshift.restclient.OpenShiftException: Unable to read endpoint https://ms-master.example.com:8443/api
    at com.openshift.internal.restclient.ApiTypeMapper.readEndpoint(ApiTypeMapper.java:205)
    at com.openshift.internal.restclient.ApiTypeMapper.getLegacyGroups(ApiTypeMapper.java:188)
    at com.openshift.internal.restclient.ApiTypeMapper.init(ApiTypeMapper.java:128)
    at com.openshift.internal.restclient.ApiTypeMapper.isSupported(ApiTypeMapper.java:116)
    at com.openshift.internal.restclient.URLBuilder.buildWithNamespaceInPath(URLBuilder.java:140)
    at com.openshift.internal.restclient.URLBuilder.build(URLBuilder.java:127)
    at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:193)
    at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:181)
    at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:269)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftScaler.coreLogic(IOpenShiftScaler.java:68)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doItCore(IOpenShiftPlugin.java:309)
    at com.openshift.jenkins.plugins.pipeline.model.IOpenShiftPlugin.doIt(IOpenShiftPlugin.java:322)
    at com.openshift.jenkins.plugins.pipeline.OpenShiftBaseStep.perform(OpenShiftBaseStep.java:91)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
    at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
    at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:49)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.execute(RealCall.java:60)
    at com.openshift.internal.restclient.ApiTypeMapper.readEndpoint(ApiTypeMapper.java:202)
    ... 21 more
Caused by: java.security.ProviderException: java.security.KeyException
    at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:147)
    at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
    at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:77)
    at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:721)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
    ... 46 more
Caused by: java.security.KeyException
    at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method)
    at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:128)
    ... 55 more
Build step 'Scale OpenShift Deployment' marked build as failure
Finished: FAILURE

**Comment by gyj0825** [comment]
I found the solution.
Solved the problem when Modify the JDK version 1.8.0-101 to 1.8.0-65 on jenkins host. 
$ java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
